matrix:
  include:
    - stage: unit_test
      language: go
      go: 1.12.x
      script: echo go job
    - stage: unit_test
      script: go env
    - &depoly
      stage: depoly
      language: python
      python: 3.7
      script: echo python 1
    - <<: *depoly
      script: echo python 2
