matrix:
  include:
    - language: go
      go: 1.12.x
      script: go env
    - language: go
      go: 1.12.x
      script: sleep 10

    - &depoly
      language: python
      python: 3.7
      script: echo python 1
    - <<: *depoly
      script: echo python 2
