matrix:
  include:
    - language: go
      go: 1.12.x
      script: go env
      dist: bionic
      addons:
        apt:
          packages:
            - ccache
      cache:
        - ccache
      before_install:
        - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install g++-6 gcc-6
    #      addons:
#        apt:
#          packages:
#            - python3-pip
#            - parallel
#            - g++-6
#            - gcc-6
#            - bzr
#            - build-essential
    - language: go
      go: 1.12.x
      script: sleep 10

    - &depoly
      language: python
      python: 3.7
      script: echo python 1
    - <<: *depoly
      script: echo python 2
