matrix:

  stages:
    - unit_test
    - depoly
  include:

    - stage: unit_test
      language: go
      go: 1.12.x
      script: go env
    - stage: depoly
      depoly: &ft_job
      language: python
      python: 3.7
      script:
        - echo ft_job
    - stage: depoly
      deploy:
        <<: *ft_job
        script: python --version
